Added the Ability to "Open" the Fairing in the Editor to allow seeing and editing the payload inside
KSP-RO/ProceduralFairings pull request #23
Opened 2021-06-23 04:55 UTC by pap1723

2021-06-23 22:22 UTC, DRVeyl requested changes

2021-06-23 22:22 UTC, DRVeyl commented on Source/ProceduralFairings/FairingBase.cs
> +                            sf.dragCubeUpdater.Update();
Don't do this here.  It doesn't clear the sides list, so every time this gets called it keeps appending all the sides that are attached.  But you really don't need to discover the sides here, anyway.  I'd undo this piece, remove the List<ProceduralFairingSide> declaration, and implement below.

2021-06-23 22:22 UTC, DRVeyl commented on Source/ProceduralFairings/FairingBase.cs
> +        }
Either go collect the list of sides in here, or write a utility method for it.  Don't run on a global list that you have to maintain.  There's several ways to write this, but a 1-line LINQ one is:
```
var sides = part.FindAttachNodes("connect").Where(x => x.attachedPart is Part sp && sp.GetComponent<ProceduralFairingSide>() is ProceduralFairingSide).ToList();
```
Also see comment above about not needing to set `editorOpenOffset.x` directly.

2021-06-23 22:22 UTC, DRVeyl commented on Source/ProceduralFairings/FairingBase.cs
> +        private float OffsetValueX => Math.Max(minOffset, Math.Max(baseSize, topSize));
Move this up to line ~127 with the things that will use it?

2021-06-23 22:22 UTC, DRVeyl commented on Source/ProceduralFairings/FairingBase.cs
> +        private float minOffset = 2f;
Trick:
`public Vector3 EditorOpenOffset => new Vector3(OffsetValueX, 0, 0);`

Then you won't have to mess with trying to set the x value manually.  Whenever you ask for the EditorOpenOffset Vector3, you will get the appropriate one.

Declare `minOffset` as `const` ie `private const float minOffset = 2`

2021-06-23 22:22 UTC, DRVeyl commented on Source/ProceduralFairings/FairingBase.cs
> +            Fields[nameof(openFairing)].uiControlEditor.onSymmetryFieldChanged = OnToggleOpen;
I guess these should be `+=` if everything else is.  (Although.. in OnStart... practically every other mod I've been involved in will do `=` during initialization.  So... well, `+=` is probably better anyway.)

2021-07-05 20:06 UTC, pap1723 commented
This Branch has been corrupted and combined, moved to a new branch.

2021-07-05 20:06 UTC, closed without merging